services:
  web:
    image: fchat:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DATABASE_HOST: "host.docker.internal:5432"
    volumes:
      - ./src/main/resources:/app/resources
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: fchat
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
volumes:
  db_data: